---
- name: Setup Environment
  hosts: localhost
  become_user: root
  vars:
    go_version: 1.18.9
    username: tschneid 
    sansible_golang_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    sansible_golang_tarball_checksum: 015692d2a48e3496f1da3328cf33337c727c595011883f6fc74f9b5a9c86ffa8

  roles:
    - role: sansible.golang

  tasks:
    - name: setup sudoless access
      lineinfile:
        state: present
        path: /etc/sudoers
        line: "{{ username }}    ALL=(ALL) NOPASSWD:ALL"
      become: yes

    - name: Setup git prefered editor
      command:
        cmd: git config --global core.editor "vim"

    - name: Create default GOPATH directory
      file:
        path: "{{ lookup('env', 'HOME') }}/go"
        state: directory

    - name: Create .vimrc
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.vimrc"
        state: touch

    - name: set vim config
      ansible.builtin.lineinfile:
        line: "{{ item }}" 
        path: "{{ lookup('env', 'HOME') }}/.vimrc"
      with_items:
        - set tabstop=2
        - set expandtab
        - set shiftwidth=2

    - name: Set variables in .bashrc
      ansible.builtin.lineinfile:
        line: "{{ item }}" 
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
      with_items:
        - "export GOPATH=$(go env GOPATH)"
        - "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin"
        - "export EDITOR='vim'"

    - name: Install required packages for ARO
      ansible.builtin.dnf:
        name:
          - python-setuptools
          - python-virtualenv 
          - gpgme-devel
          - libassuan-devel 
          - openssl
          - podman
          - podman-docker
          - azure-cli
          - graphviz
          - gv
      become: yes

    - name: Grab kubectl binary
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.24.1/bin/linux/amd64/kubectl
        dest: /usr/local/bin
        mode: 0755
      become: yes

    - name: Install packages for vagrant
      ansible.builtin.dnf:
        state: present
        name:
          - '@virtualization'
          - qemu-kvm
          - libvirt
          - libguestfs-tools
          - virt-install
          - rsync
          - vagrant
          - vagrant-libvirt
      become: yes

    # - name: Set user for QEMU processes
    #   replace:
    #     path: /etc/libvirt/qemu.conf
    #     regexp: '^#.*user = \"\+0\".*'
    #     replace: '\1'
    #   become: yes
    - name: Set user for QEMU processes
      ansible.builtin.lineinfile:
        line: 'user = "+0"'
        path: /etc/libvirt/qemu.conf
      become: yes

    - name: start service "{{ item }}"
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - virtnetworkd
        - libvirtd
      become: yes

# Add user to group, prevents being prompted for password
# sudo usermod -a -G libvirt $(whoami)
