---
- name: Setup Environment
  hosts: localhost
  become_user: root
  vars:
    go_version: 1.17.11
    username: tschneid 
    sansible_golang_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    sansible_golang_tarball_checksum: d69a4fe2694f795d8e525c72b497ededc209cb7185f4c3b62d7a98dd6227b3fe

  roles:
    - role: sansible.golang

  tasks:
    - name: setup sudoless access
      lineinfile:
        state: present
        path: /etc/sudoers
        line: "{{ username }}    ALL=(ALL) NOPASSWD:ALL"
      become: yes

    - name: Setup git prefered editor
      command:
        cmd: git config --global core.editor "vim"

    - name: Create default GOPATH directory
      file:
        path: "{{ lookup('env', 'HOME') }}/go"
        state: directory

    - name: Add GOPATH and go/bin PATH to .bashrc
      ansible.builtin.lineinfile:
        line: "{{ item }}" 
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
      with_items:
        - "export GOPATH=$(go env GOPATH)"
        - "export PATH=$PATH:/usr/local/go/bin"

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - python-setuptools
          - python-virtualenv 
          - gpgme-devel
          - libassuan-devel 
          - openssl
          - podman
          - podman-docker
          - azure-cli
      become: yes

